"""Data models for the JARVIS Smart Suggestions Engine."""

import enum
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional


class SuggestionCategory(enum.Enum):
    """Categories of suggestions."""
    COMMIT = "commit"
    BUG = "bug"
    FEATURE = "feature"
    PERFORMANCE = "performance"
    DOCUMENTATION = "documentation"
    REFACTOR = "refactor"
    TEST = "test"
    REMINDER = "reminder"


class SuggestionPriority(enum.Enum):
    """Priority levels for suggestions."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


@dataclass
class Suggestion:
    """Represents a single suggestion generated by the engine."""
    id: str
    timestamp: datetime
    title: str
    description: str
    confidence: float  # 0-1
    category: SuggestionCategory
    priority: SuggestionPriority
    dismissed: bool = False
    acknowledged: bool = False
    auto_dismiss_threshold: float = 0.3

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat(),
            "title": self.title,
            "description": self.description,
            "confidence": self.confidence,
            "category": self.category.value,
            "priority": self.priority.value,
            "dismissed": self.dismissed,
            "acknowledged": self.acknowledged,
            "auto_dismiss_threshold": self.auto_dismiss_threshold,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Suggestion":
        """Create from dictionary."""
        return cls(
            id=data["id"],
            timestamp=datetime.fromisoformat(data["timestamp"]),
            title=data["title"],
            description=data["description"],
            confidence=data["confidence"],
            category=SuggestionCategory(data["category"]),
            priority=SuggestionPriority(data["priority"]),
            dismissed=data.get("dismissed", False),
            acknowledged=data.get("acknowledged", False),
            auto_dismiss_threshold=data.get("auto_dismiss_threshold", 0.3),
        )


@dataclass
class SuggestionStats:
    """Statistics about suggestion generation and usage."""
    total_generated: int = 0
    total_dismissed: int = 0
    acceptance_rate: float = 0.0
    by_category: Dict[str, int] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "total_generated": self.total_generated,
            "total_dismissed": self.total_dismissed,
            "acceptance_rate": self.acceptance_rate,
            "by_category": dict(self.by_category),
        }
